dataset: KITTI
dataset_params:
  path: /mnt/sda/hyh/data//eval/KITTI
  width: 640
  height: 480
  split: .index.txt
  depth_unit: 1.0
model_name: DiffE2EFT
eval_depth:
  metric_names:
  - Abs Rel
  - delta < 1.25
  - delta < 1.25^2
  - delta < 1.25^3
  disp_input: false
vis_depth: false
save_dir: results/diffe2eft/eval_diffe2eft-dep_lstq_KITTI
metric_scale: true
model_params:
  pseudo_arg: placeholder
