dataset: ETH3D
dataset_params:
  path: /mnt/pfs/data/RGBD/moge_eval//ETH3D
  width: 2048
  height: 1365
  split: .index.txt
  include_segmentation: true
  depth_unit: 1
model_name: UniDepth
model_params:
  model_dir: /mnt/pfs/users/sunyangtian/Depth/UniDepth
  ckpt_path: /mnt/pfs/share/pretrained_model/unidepth-v1-vitl14
eval_depth:
  metric_names:
  - Abs Rel
  - delta < 1.25
  - delta < 1.25^2
  - delta < 1.25^3
  metric_scale: true
vis_depth: false
save_dir: eval_unidepth_ETH3D
