dataset: Sintel
dataset_params:
  path: /mnt/sda/yzy/Depth_Survey/data/Sintel
  width: 872
  height: 436
  split: .index.txt
  has_sharp_boundary: true
  include_segmentation: true
model_name: GeoWizard
model_params:
  model_dir: /mnt/sda/yzy/Git_Project/GeoWizard
  ckpt_path: /mnt/sda/yzy/Git_Project/pretrained/Geowizard
eval_depth:
  metric_names:
  - Abs Rel
  - delta < 1.25
  - delta < 1.25^2
  - delta < 1.25^3
  depth_alignment: lstsq
  metric_scale: false
  disp_input: false
vis_depth: false
save_dir: eval_geowizard-align_Sintel
