dataset: KITTI
dataset_params:
  path: /mnt/sda/hyh/data//eval/KITTI
  width: 640
  height: 480
  split: .index.txt
  depth_unit: 1.0
model_name: GenPercept
eval_depth:
  metric_names:
  - Abs Rel
  - delta < 1.25
  - delta < 1.25^2
  - delta < 1.25^3
  disp_input: false
  metric_scale: false
  depth_alignment: lstsq
vis_depth: false
save_dir: results/genpercept/eval_genpercept-dep_lstq_KITTI
model_params:
  model_dir: /mnt/sda/hyh/depth/GenPercept
  pretrained_path: /mnt/sda/hyh/depth/GenPercept/pretrained_weights/stable-diffusion-2-1
  unet_path: /mnt/sda/hyh/depth/GenPercept/weights/genpercept-models/unet_depth_v2
