dataset: NYUv2ImgDataset
dataset_params:
  dir: /mnt/pfs/data/RGBD/marigold_eval/nyuv2/nyu_labeled_extracted.tar
  disp_name: nyu_depth_test_full
  filenames: dataset/nyuv2Img/filename_list_test.txt
  eigen_valid_mask: true

model_name: "UniDepth"
model_params:
  model_dir: "/mnt/pfs/users/sunyangtian/Depth/UniDepth"
  ckpt_path: "/mnt/pfs/share/pretrained_model/unidepth-v1-vitl14"

eval_depth:
  metric_names: 
    - 'Abs Rel'
    - 'delta < 1.25'
    - 'delta < 1.25^2'
    - 'delta < 1.25^3'
  metric_scale: True

vis_depth: True
save_dir: debug_unidepth_nyuv2