dataset: ETH3D
dataset_params:
  path: /mnt/sda/hyh/data//eval/ETH3D
  width: 640
  height: 480
  split: .index.txt
  depth_unit: 1.0
model_name: MiDasV31
eval_depth:
  metric_names:
  - Abs Rel
  - delta < 1.25
  - delta < 1.25^2
  - delta < 1.25^3
  disp_input: false
  metric_scale: false
  depth_alignment: lstsq
vis_depth: false
save_dir: results/midasv31/eval_midasv31-dep_lstq_ETH3D
model_params:
  model_dir: /mnt/sda/hyh/depth/MiDaS
  model_ckpt_path: /mnt/sda/hyh/depth/MiDaS/ckpt/dpt_beit_large_512.pt
