dataset: NYUv2
dataset_params:
  path: /mnt/sda/yzy/Depth_Survey/data/NYUv2
  width: 640
  height: 480
  split: .index.txt
  depth_unit: 1.0
model_name: LeReS
model_params:
  model_dir: /mnt/sda/yzy/Git_Project/AdelaiDepth/LeReS/Minist_Test
  ckpt_path: /mnt/sda/yzy/Git_Project/pretrained/res101.pth
eval_depth:
  metric_names:
  - Abs Rel
  - delta < 1.25
  - delta < 1.25^2
  - delta < 1.25^3
  depth_alignment: lstsq
  metric_scale: false
  disp_input: false
vis_depth: false
save_dir: eval_leres-align_NYUv2
