dataset: HAMMER
dataset_params:
  path: /mnt/pfs/data/RGBD/moge_eval/HAMMER
  width: 1664
  height: 832
  split: ".index.txt"
  has_sharp_boundary: true
  depth_unit: 1.0


model_name: "Marigold"
model_params:
  model_dir: "/mnt/pfs/users/sunyangtian/Depth/Marigold"
  ckpt_path: "/mnt/pfs/share/pretrained_model/marigold-depth-v1-1"
  denoise_steps: 1
  ensemble_size: 1
  half_precision: False
  processing_res: 0
  output_processing_res: False
  resample_method: bilinear
  color_map: Spectral


eval_depth:
  metric_names: 
    - 'Abs Rel'
    - 'delta < 1.25'
    - 'delta < 1.25^2'
    - 'delta < 1.25^3'
  depth_alignment: "lstsq"
  metric_scale: False

vis_depth: True
save_dir: eval_marigold_HAMMER