dataset: GSO
dataset_params:
  path: /mnt/sda/hyh/data//eval/GSO
  width: 640
  height: 480
  split: .index.txt
  depth_unit: 1.0
model_name: Metric3Dv2
eval_depth:
  metric_names:
  - Abs Rel
  - delta < 1.25
  - delta < 1.25^2
  - delta < 1.25^3
  disp_input: false
  metric_scale: true
  depth_alignment: lstsq
vis_depth: false
save_dir: results/metric3dv2/eval_metric3dv2-metric_GSO
model_params:
  pseudo_arg: placeholder
