dataset: NYUv2
dataset_params:
  path: /home/muxin/Depth_Project/Depth_Survey/dataset/eval/NYUv2
  width: 640
  height: 480
  split: .index.txt
  depth_unit: 1.0
model_name: DepthPro
model_params:
  model_dir: /home/muxin/Depth_Project/ml-depth-pro
  ckpt_path: /home/muxin/Depth_Project/ml-depth-pro/checkpoints/depth_pro.pt
  encoder: vitl
eval_depth:
  metric_names:
  - Abs Rel
  - delta < 1.25
  - delta < 1.25^2
  - delta < 1.25^3
  depth_alignment: lstsq
  metric_scale: false
  disp_input: false
vis_depth: false
save_dir: eval_depthpro-depth-align_NYUv2
